const Women = 
[
    {
        id:1,
        image:'Images/Women/shoe1.png',
        title:'Petza',
        price:'$9.45',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        source:'Boot',
    },
    {
        id:2,
        image:'Images/Women/shoe2.png',
        title:'Jero Bliss',
        price:'$10.00',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Boot',
    },
    {
        id:3,
        image:'Images/Women/shoe3.png',
        title:'Zoe Shoe',
        price:'$8.10',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Boot',
    },
    {
        id:4,
        image:'Images/Women/shoe4.png',
        title:'Toto Cart',
        price:'$9.89',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        source:'Boot',
    },
    {
        id:5,
        image:'Images/Women/shoe5.png',
        title:'Opocal',
        price:'$7.22',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        source:'Boot',
    },
    {
        id:6,
        image:'Images/Women/shoe6.png',
        title:'Track Zeca',
        price:'$7.05',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        source:'Boot',
    },
    {
        id:7,
        image:'Images/Women/shoe7.png',
        title:'Prompt Boot',
        price:'$10.11',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Boot',
    },
    {
        id:8,
        image:'Images/Women/shoe10.png',
        title:'Lion Boot',
        price:'$10.67',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star"></i>,
        source:'Boot',
    },
    {
        id:9,
        image:'Images/Women/shoe8.png',
        title:'Hiroko Fresh',
        price:'$8.00',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Boot',
    },
    {
        id:10,
        image:'Images/Women/shoe9.png',
        title:'Moto Don',
        price:'$7.32',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Boot',
    },
    {
        id:11,
        image:'Images/Women/slip1.png',
        title:'Dock',
        price:'$4.45',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:12,
        image:'Images/Women/slip2.png',
        title:'Zoto Slip',
        price:'$2.09',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:13,
        image:'Images/Women/slip3.png',
        title:'Simple Slip',
        price:'$1.89',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:14,
        image:'Images/Women/slip4.png',
        title:'Tor Slip',
        price:'$3.21',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:15,
        image:'Images/Women/slip5.png',
        title:'Zeca',
        price:'$5.00',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:16,
        image:'Images/Women/slip6.png',
        title:'Flite Cart',
        price:'$5.78',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:17,
        image:'Images/Women/slip7.png',
        title:'Cover Slip',
        price:'$2.85',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:18,
        image:'Images/Women/slip8.png',
        title:'Wool Slip',
        price:'$4.08',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:19,
        image:'Images/Women/slip9.png',
        title:'Bliss Dome',
        price:'$3.90',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
    {
        id:20,
        image:'Images/Women/slip10.png',
        title:'Sparx Slip',
        price:'$4.77',
        star1: <i class="fa-sharp fa-solid fa-star"></i>,
        star2: <i class="fa-sharp fa-solid fa-star"></i>,
        star3: <i class="fa-sharp fa-solid fa-star"></i>,
        star4: <i class="fa-sharp fa-solid fa-star"></i>,
        star5: <i class="fa-sharp fa-solid fa-star"></i>,
        star6: <i class="fa-sharp fa-solid fa-star-half-stroke"></i>,
        source:'Slipper',
    },
];

export default Women;
